// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 原来的「编译局」一个栏位，现在一分为二：施工中 / 已完成。
  //
  // 对应关系（改这三处要一起改）：
  //   1. 这里定义的 sidebar 名
  //   2. docusaurus.config.js 里 navbar 的 {type:'docSidebar', sidebarId: ...}
  //   3. 文档实际所在的目录名（dirName）
  //
  // 两栏各自内容用 autogenerated 指向对应目录，所以新增文档只要丢进目录即可，
  // 本文件和 docusaurus.config.js 都不用改。
  //
  // 脚手架文档（intro.mdx、tutorial-basics/、tutorial-extras/）刻意没有被任何
  // sidebar 引用：文件与页面都保留，只是不再出现在导航与侧边栏里。

  inProgressSidebar: [
    {
      type: 'category',
      label: '施工中',
      // 该栏位下只有一个分类，不需要折叠，常驻展开
      collapsible: false,
      items: [{type: 'autogenerated', dirName: 'in-progress'}],
    },
  ],

  completedSidebar: [
    {
      type: 'category',
      label: '已完成',
      collapsible: false,
      items: [{type: 'autogenerated', dirName: 'completed'}],
    },
  ],
};

export default sidebars;
